name: pangram
version: 2.0.0.12

dependencies:
  - base
  - text

library:
  exposed-modules: Pangram
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pangram
      - hspec
